### ISSUE TITLE
Don't depend on Elm

### ISSUE THREAD

**Issue by norpan** [pdamoc/elm-ports-driver#1]
Your package.json has a dependency on elm, which downloads the whole elm platform to node_modules when you do npm install.

**Comment by norpan** [comment]
I ended up not using npm at all, instead doing
```
import elm_ports_driver from 'elm-stuff/packages/pdamoc/elm-ports-driver/3.0.0/index.js'
```

**Comment by pdamoc** [comment]
I have not considered this approach but I guess it would work just fine.

**Comment by norpan** [comment]
It does indeed work, but only if you know the version exactly

**Comment by pdamoc** [comment]
It's a hack and I guess it cannot be easily automated in an install script. 

So... fine for trying things out but maybe not the best approach for production.
