### ISSUE TITLE
.npmignore example

### ISSUE THREAD

**Issue by norpan** [pdamoc/elm-ports-driver#3]
I just noted that after npm install, it also installed the dependencies in the `example` directory, so it took quite some time. It added 177 kB and 24000 files.

I think `example` should be added to the `.npmignore` file to avoid this. Maybe also `src` and `elm-package.json`.

**Comment by pdamoc** [comment]
Can you provide more information about the context? I tried an `npm install elm-ports-driver` in a new folder and it installed only one package (I'm on OS X).

**Comment by norpan** [comment]
Look in the node_modules/elm-ports-driver/example/node_modules folder

**Comment by pdamoc** [comment]
I see it now. I have added the `example`, `src` and `elm-package.json` to `.npmignore`. 

Thank you!
